# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - gtime -v python -X tracemalloc=25 -c "print('test interpreter')" 2>&1 | tee "results/python.txt"
      - gtime -v python -X tracemalloc=25 base_ply.py 2>&1 | tee "results/ply-version-{{.TS}}.txt"
      - gtime -v python -X tracemalloc=25 base_rply.py 2>&1 | tee "results/rply-version-{{.TS}}.txt"
    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"
