# https://taskfile.dev

version: '3'

includes:
  ply:
    taskfile: ./1-ply-plain/Taskfile.yaml
    dir: ./1-ply-plain
  pegen:
    taskfile: ./6-pegen-tst/Taskfile.yaml
    dir: ./6-pegen-tst
  libsct:
    taskfile: ./7-1-libcst-test/Taskfile.yaml
    dir: ./7-1-libcst-test

tasks:
  update-cpython-pegen:
    cmds:
# todo: should move to git-diff version https://stackoverflow.com/questions/23937436
      - git fetch --depth=1 https://github.com/python/cpython.git main:tmp_cpython_main
      - git checkout tmp_cpython_main
      - git subtree split --prefix=Tools/peg_generator -b subtree_split_branch
      - git checkout -
      - git subtree add --prefix=9-cpy-pegen subtree_split_branch
      - git branch -D subtree_split_branch tmp_cpython_main

    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"
