# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - python 1-xonsh-parser.py | tee "results/xonsh-parser-{{.TS}}.md"
      - python 2-ctx-parser.py | tee "results/ctx-parser-{{.TS}}.md"
    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"

  generate-parser:
    cmds:
      - python tasks/generate.py
