# https://taskfile.dev

version: '3'


tasks:
  generate-parser:
    cmds:
      - python task_generate_parser.py

  profile-memory:
    cmds:
      - python task_profile_mem.py | tee "results-xonsh-parser-{{.TS}}.log"
    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"
