# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - python main.py 2>&1 | tee "run-results-{{.TS}}.log"
      - python main_regex.py 2>&1 | tee "run-results-regex-{{.TS}}.log"
    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"

  gen-parser:
    cmds:
      # this saves the generated parser to `parse.py`
      - python -m pegen python.gram > python.gram.out
      - black parse.py

  mypycify:
    cmds:
      - mypy --strict parse.py
      - python3 setup.py build_ext --inplace
