# https://taskfile.dev

version: '3'

vars:
  TS:
    sh: date "+%Y%m%d-%H%M%S"

tasks:
  json-generate:
    cmds:
      - python -m lark.tools.standalone json.lark > json_parser.py
    dir: json-example
  json-bench:
    cmds:
      - gtime --verbose python json_parser_main.py sample.json | tee result.{{.TS}}.log
    dir: json-example
  py-bench:
    cmds:
      - gtime --verbose python parser.py parser.py | tee result.{{.TS}}.log
    dir: py-example
