# https://taskfile.dev

version: '3'


tasks:
  default:
    deps:
      - task: cythonize
#      - task: mypycify
    cmds:
      - python xonsh_parser.py 2>&1 | tee "xonsh-parser-{{.TS}}.log"
    vars:
      TS:
        sh: date "+%Y%m%d-%H%M%S"
  clean:
    cmds:
      - find ply -name "*.c" -delete
      - find ply -name "*.so" -delete
  cythonize:
    cmds:
      - cythonize -3 -i ply/yacc_mini.pxd
    sources:
      - ply/yacc_mini.py*
    generates:
      - ply/yacc_mini.so
      - ply/yacc_mini.c
  mypycify:
    cmds:
      - mypyc ply/yacc_mini.py
    sources:
      - ply/yacc_mini.py
    generates:
      - ply/yacc_mini.so
      - ply/yacc_mini.c